services:
  tunnel:
    image: cloudflare/cloudflared
    restart: always
    env_file:
      - v4.env
    command: tunnel run
    networks:
      - cloudflare

  storage:
    restart: always
    volumes:
      - storage-data:/data
      - storage-events:/opt/minio/events
    env_file:
      - v4.env
    depends_on:
      - redis
    networks:
      - cloudflare
      - default
    ports:
      - 100.115.138.95:9000:9000
      - 100.115.138.95:9001:9001

  redis:
    restart: always
    volumes:
      - redis:/data
    ports:
      - 100.115.138.95:6379:6379

  mysql:
    restart: always
    volumes:
      - mysql:/var/lib/mysql
    env_file:
      - v4.env
    ports:
      - 100.115.138.95:3306:3306

  lurker:
    image: ghcr.io/aaa4xu/mirvworld/lurker
    restart: always
    env_file:
      - v4.env
    environment:
      - LURKER_LOBBY_INTERVAL=1000
    dns:
      - 100.100.100.100
    dns_search:
      - elf-chameleon.ts.net

  frontend:
    image: ghcr.io/aaa4xu/mirvworld/frontend
    restart: always
    env_file:
      - v4.env
    networks:
      - cloudflare
      - default

  matches:
    image: ghcr.io/aaa4xu/mirvworld/matches
    restart: always
    env_file:
      - v4.env
    ports:
      - 100.115.138.95:3700:80

  gamelens:
    image: ghcr.io/aaa4xu/mirvworld/gamelens
    restart: always
    environment:
      - GAMELENS_REDIS_URL=redis://redis:6379
    env_file:
      - v4.env
    depends_on:
      - redis
      - storage
    cpus: 24

volumes:
  storage-data:
  storage-events:
  redis:
  mysql:

networks:
  cloudflare: