services:
  tunnel:
    image: cloudflare/cloudflared
    restart: always
    env_file:
      - v4.env
    command: tunnel run
    networks:
      - cloudflare

  storage:
    restart: always
    volumes:
      - storage-data:/data
      - storage-events:/opt/minio/events
    env_file:
      - v4.env
    depends_on:
      - redis
    networks:
      - cloudflare
      - default
    ports:
      - 100.115.138.95:9000:9000
      - 100.115.138.95:9001:9001

  redis:
    restart: always
    volumes:
      - redis:/data
    ports:
      - 100.115.138.95:6379:6379

  lurker:
    image: ghcr.io/aaa4xu/mirvworld/lurker@sha256:9c3dab4e9a5a2c7f2d656f67b44d10b4edb8c5580ab0f89e0e0dea92f43bfaf6
    restart: always
    env_file:
      - v4.env
    environment:
      - LURKER_LOBBY_INTERVAL=1100
      - LURKER_OPENFRONT_SERVER_ENDPOINT=http://gateway-prod
    depends_on:
      - gateway-prod

  lurker-dev:
    image: ghcr.io/aaa4xu/mirvworld/lurker
    restart: always
    env_file:
      - v4.env
    environment:
      - LURKER_LOBBY_INTERVAL=1100
      - LURKER_OPENFRONT_SERVER_ENDPOINT=http://gateway-dev
      - LURKER_REDIS_URL=redis://localhost:6379/1
    depends_on:
      - gateway-dev

  frontend:
    image: ghcr.io/aaa4xu/mirvworld/frontend
    restart: always
    env_file:
      - v4.env
    environment:
      - PROTOCOL_HEADER=x-forwarded-proto
      - HOST_HEADER=x-forwarded-host
      - ORIGIN=https://mirv.world
      - ADDRESS_HEADER=cf-connecting-ip
    networks:
      - cloudflare
      - default

  matches:
    image: ghcr.io/aaa4xu/mirvworld/matches
    restart: always
    env_file:
      - v4.env
    ports:
      - 100.115.138.95:3700:80

  gamelens:
    image: ghcr.io/aaa4xu/mirvworld/gamelens
    restart: always
    environment:
      - GAMELENS_REDIS_URL=redis://redis:6379
    env_file:
      - v4.env
    depends_on:
      - redis
      - storage
    cpus: 24

  mongodb:
    restart: always
    volumes:
      - ./docker/mongod.yaml:/etc/mongo/mongod.conf:ro
      - mongodb:/data/db
    env_file:
      - v4.env
    ports:
      - 100.115.138.95:27017:27017
    command: ["mongod", "--config", "/etc/mongo/mongod.conf"]

  gateway-prod:
    image: ghcr.io/aaa4xu/mirvworld/gateway:latest
    restart: always
    env_file:
      - v4.env
    ports:
      - 100.115.138.95:3110:80

  gateway-dev:
    image: ghcr.io/aaa4xu/mirvworld/gateway:latest
    restart: always
    environment:
      - GW_ENDPOINT=https://main.openfront.dev
    env_file:
      - v4.env
    ports:
      - 100.115.138.95:3120:80

volumes:
  storage-data:
  storage-events:
  redis:
  mongodb:

networks:
  cloudflare: