services:
  tunnel:
    image: cloudflare/cloudflared
    restart: always
    env_file:
      - v4.env
    command: tunnel run
    networks:
      - cloudflare

  storage:
    restart: always
    volumes:
      - storage:/data
      - storage-events:/opt/minio/events
    env_file:
      - v4.env
    environment:
      - MINIO_COMPRESSION_ENABLE=on
    networks:
      - cloudflare
      - default
    ports:
      - 127.0.0.1:10001:9001

  lurker:
    restart: always
    env_file:
      - v4.env
    environment:
      - LURKER_LOBBY_INTERVAL=1000
      - LURKER_REDIS_URL=redis://redis:6379

  redis:
    restart: always
    volumes:
      - redis:/data
    ports:
      - 127.0.0.1:10002:6379

  game-snapshot-v0-23-16:
    restart: always
    networks:
      - cloudflare

volumes:
  storage:
  storage-events:
  redis:

networks:
  cloudflare: