services:
  storage:
    image: quay.io/minio/minio:RELEASE.2025-04-22T22-12-26Z
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      - MINIO_COMPRESSION_ENABLE=on
      # Legacy
      - MINIO_NOTIFY_REDIS_ENABLE_PRIMARY=on
      - MINIO_NOTIFY_REDIS_ADDRESS_PRIMARY=redis:6379
      - MINIO_NOTIFY_REDIS_KEY_PRIMARY=storage:bucketevents
      - MINIO_NOTIFY_REDIS_FORMAT_PRIMARY=access
      - MINIO_NOTIFY_REDIS_QUEUE_DIR_PRIMARY=/opt/minio/events
      # Matches service
      - MINIO_NOTIFY_REDIS_ENABLE_MATCHES=on
      - MINIO_NOTIFY_REDIS_ADDRESS_MATCHES=redis:6379
      - MINIO_NOTIFY_REDIS_KEY_MATCHES=matches:storage
      - MINIO_NOTIFY_REDIS_FORMAT_MATCHES=access
      - MINIO_NOTIFY_REDIS_QUEUE_DIR_MATCHES=/opt/minio/events/matches
      # Gamelens
      - MINIO_NOTIFY_REDIS_ENABLE_GAMELENS=on
      - MINIO_NOTIFY_REDIS_ADDRESS_GAMELENS=redis:6379
      - MINIO_NOTIFY_REDIS_KEY_GAMELENS=gamelens:storage
      - MINIO_NOTIFY_REDIS_FORMAT_GAMELENS=access
      - MINIO_NOTIFY_REDIS_QUEUE_DIR_GAMELENS=/opt/minio/events/gamelens

  lurker:
    image: mirvworld/lurker
    restart: unless-stopped
    environment:
      - LURKER_REDIS_URL=redis://redis:6379
    depends_on:
      - redis
      - storage

  frontend:
    image: mirvworld/frontend
    restart: unless-stopped
    depends_on:
      - redis
      - matches

  redis:
    image: redis:8-alpine
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning

  gamelens:
    image: mirvworld/gamelens
    restart: unless-stopped

  matches:
    image: mirvworld/gamelens
    restart: unless-stopped
    environment:
      - MATCHES_REDIS_URL=redis://redis:6379
    depends_on:
      - redis
      - storage
      - mysql

  mongodb:
    image: mongodb/mongodb-community-server
    restart: unless-stopped