services:
  storage:
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./storage/docker/storage/data:/data
      - ./storage/docker/storage/events:/opt/minio/events
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin

  redis:
    volumes:
      - ./storage/docker/redis:/data
    ports:
      - 6379:6379

  frontend:
    build:
      context: .
      dockerfile: packages/frontend/Dockerfile
    ports:
      - 4173:80

  db:
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretpassword
    volumes:
      - ./storage/docker/mysql:/var/lib/mysql

  game-snapshot-v0-23-16:
    ports:
      - 12316:80

  gamelens:
    build:
      context: .
      dockerfile: packages/gamelens/Dockerfile
    depends_on:
      - redis
      - storage

  lurker:
    build:
      context: .
      dockerfile: packages/lurker/Dockerfile