services:
  storage:
    image: quay.io/minio/minio:RELEASE.2025-04-22T22-12-26Z
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      - MINIO_COMPRESSION_ENABLE=on
      - MINIO_NOTIFY_REDIS_ENABLE_PRIMARY=on
      - MINIO_NOTIFY_REDIS_ADDRESS_PRIMARY=redis:6379
      - MINIO_NOTIFY_REDIS_KEY_PRIMARY=storage:bucketevents
      - MINIO_NOTIFY_REDIS_FORMAT_PRIMARY=access
      - MINIO_NOTIFY_REDIS_QUEUE_DIR_PRIMARY=/opt/minio/events

  lurker:
    image: mirvworld/lurker
    build:
      context: .
      dockerfile: packages/lurker/Dockerfile
    restart: unless-stopped
    depends_on:
      - redis
      - storage

  redis:
    image: redis:8-alpine
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning

  game-snapshot-v0-23-16:
    image: mirvworld/game-snapshot:v0.23.16
    build:
      context: .
      dockerfile: packages/game-snapshot/Dockerfile
      args:
        - GIT_COMMIT=4339644
    restart: unless-stopped
    environment:
      - NGINX_STORAGE_PREFIX=http://storage:9000/replays/4339644