services:
  tunnel:
    image: cloudflare/cloudflared
    restart: always
    env_file:
      - v4.env
    command: tunnel run
    networks:
      - cloudflare

  storage:
    restart: always
    volumes:
      - storage:/data
    env_file:
      - v4.env
    environment:
      - MINIO_COMPRESSION_ENABLE=on
    networks:
      - cloudflare
      - default
    ports:
      - 127.0.0.1:9001:9001

  lurker:
    restart: always
    env_file:
      - v4.env
    volumes:
      - lurker:/app/storage

volumes:
  storage:
  lurker:

networks:
  cloudflare: