services:
  storage:
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./storage/docker/storage:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin

  lurker:
    volumes:
      - ./storage/docker/lurker:/app/storage
    environment:
      - LURKER_S3_KEY_ID=minioadmin
      - LURKER_S3_SECRET=minioadmin