services:
  tunnel:
    image: cloudflare/cloudflared
    restart: always
    env_file:
      - v4.env
    command: tunnel run
    networks:
      - cloudflare

  storage:
    restart: always
    volumes:
      - storage:/data
      - storage-events:/opt/minio/events
    env_file:
      - v4.env
    environment:
      - MINIO_COMPRESSION_ENABLE=on
    networks:
      - cloudflare
      - default
    ports:
      - 100.111.103.57:9000:9000
      - 100.111.103.57:9001:9001

  lurker:
    restart: always
    env_file:
      - v4.env
    environment:
      - LURKER_LOBBY_INTERVAL=1000

  redis:
    restart: always
    volumes:
      - redis:/data
    ports:
      - 100.111.103.57:6379:6379

  game-snapshot-v0-23-16:
    restart: always
    networks:
      - cloudflare

volumes:
  storage:
  storage-events:
  redis:

networks:
  cloudflare: