services:
  tunnel:
    image: cloudflare/cloudflared
    restart: always
    env_file:
      - .env.production.local
    command: tunnel run
    networks:
      - cloudflare

  frontend:
    image: nginx:1.29-alpine
    restart: always
    networks:
      - cloudflare

  backend:
    image: mirvworld/backend
    restart: always
    build:
      context: .
      dockerfile: packages/backend/Dockerfile
    volumes:
      - backend-db:/app/storage/db
      - backend-replays:/app/storage/replays

networks:
  cloudflare:

volumes:
  backend-db:
  backend-replays: