services:
  storage:
    image: quay.io/minio/minio:RELEASE.2025-04-22T22-12-26Z
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      - MINIO_COMPRESSION_ENABLE=on

  lurker:
    image: mirvworld/lurker
    build:
      context: .
      dockerfile: packages/lurker/Dockerfile
    restart: unless-stopped