name: CI

on:
  push:
    branches:
      - main

permissions:
  actions: read
  contents: read
  packages: write

jobs:
  deploy:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0
          submodules: 'true' # disable recursive cloning

      - name: Install bun
        uses: oven-sh/setup-bun@v2

      - name: Install npm dependencies
        run: bun install

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v4

      - name: Test commit
        run: bunx nx affected -t lint test build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker images
        run: INPUT_GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} bunx nx affected --base=$NX_BASE --head=$NX_HEAD --target=container --parallel=2