name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0
          submodules: 'true' # disable recursive cloning

      - name: Install bun
        uses: oven-sh/setup-bun@v2

      - name: Install npm dependencies
        run: bun install

      - name: Sets SHAs required for the nx affected commands
        uses: nrwl/nx-set-shas@v4

      - name: Validate commit
        run: bunx nx affected -t lint test build